#!/usr/bin/env bash
go version || exit 1

export GOROOT=$(echo ${GOROOT})
export GOPATH=$(echo ${GOPATH})

[[ "${GOPATH}" != "" ]] || export GOPATH=/go

export PACKAGE_BIN=/usr/src/tools
export PATH=${PACKAGE_BIN}:${GOPATH}/bin:${PATH}
export CC=${CC}
export CGO_ENABLED=${CGO_ENABLED}
export GO111MODULE=${GO111MODULE}

if [[ ! -e "go.mod" ]]
then
  go mod init
  go mod tidy -go=1.17
  go mod tidy -go=1.18
fi

go mod download all
go mod vendor
