#!/usr/bin/env bash

go version || exit $?
go mod download || exit $?
go mod vendor || exit $?

LISTFILE=$(git ls-files -m | grep -vP "^$")

export GOROOT=$(echo ${GOROOT})
export GOPATH=$(echo ${GOPATH})

[[ "${GOPATH}" != "" ]] || export GOPATH=/go

export PACKAGE_BIN=/usr/src/tools
export PATH=${PACKAGE_BIN}:${GOPATH}/bin:${PATH}
export CC=${CC}
export CGO_ENABLED=${CGO_ENABLED}
export GO111MODULE=${GO111MODULE}

echo -e "\n\t >>> Reformat sources..."

for gofile in $(find . -type f -name '*.go' | grep -v '/vendor/' | grep -v '/test/' );
do
  echo -e "Checking Format file ${gofile}..."
  go fmt ${gofile}
  goimports -w ${gofile}
done

FRMFILE=$(git ls-files -m | grep -vP "^$")
for PKG in ${LISTFILE}
do
  FRMFILE=$(echo -ne "${FRMFILE}" | grep -vP "^${PKG}$" | grep -vP "^$")
done

if [[ "$(echo -ne "${FRMFILE}" | wc -l)" != "0" ]]
then
  echo -e "\n\n\t>>> This file need to be formatted with gofmt & goimports ($(echo -ne "${FRMFILE}" | wc -l) files impacted): "
  echo -e "${FRMFILE}"
  echo -e "\n\n"
  exit 1
fi

exit 0
