#!/usr/bin/env bash
go version || exit 1
                                                                                                                                                                                                                                                  export PACKAGE_BIN=/usr/src/tools                                                                                                                                                                                                                 export PATH=${PACKAGE_BIN}:${GOPATH}/bin:${PATH}
export GOROOT=$(echo ${GOROOT})
export GOPATH=$(echo ${GOPATH})
[[ "${GOPATH}" != "" ]] || export GOPATH=/go
export PACKAGE_BIN=/usr/src/tools
export PATH=${PACKAGE_BIN}:${GOPATH}/bin:${PATH}
export CC=${CC}
export CGO_ENABLED=${CGO_ENABLED}
export GO111MODULE=${GO111MODULE}

echo -e "\n\t >>> Reformat sources..."

for gofile in $(find . -type f -name '*.go' | grep -v '/vendor/' );
do
  go fmt ${gofile}
  goimports -w ${gofile}
done

git status

[ "$(git ls-files -m | wc -l)" = "0" ] || exit 1
exit 0
