#!/usr/bin/env bash
go version || exit 1

export GOROOT=$(echo ${GOROOT})
export GOPATH=$(echo ${GOPATH})
[[ "${GOPATH}" != "" ]] || export GOPATH=/go
export PACKAGE_BIN=/usr/src/tools
export PATH=${PACKAGE_BIN}:${GOPATH}/bin:${PATH}
export CC=${CC}
export CGO_ENABLED=${CGO_ENABLED}
export GO111MODULE=${GO111MODULE}

PARAMS=""

if [[ "$@" != "" ]];
then
  for VAL in $@
  do
    PARAMS+=" --skip-dirs=\"${VAL}\""
  done
fi

if [[ -e ".golangci.yml" ]];
then 
  golangci-lint run 
else 
  golangci-lint run --no-config ${PARAMS} --skip-dirs="vendors" --color="always" --print-issued-lines --print-linter-name --issues-exit-code=0 --deadline=30m --enable-all --disable=gochecknoinits --disable=gochecknoglobals --disable=wsl --disable=golint --disable=gocritic --disable=stylecheck --disable=whitespace
fi
