#!/usr/bin/env bash
go version || exit 1

export GOROOT=$(echo ${GOROOT})
export GOPATH=$(echo ${GOPATH})

[[ "${GOPATH}" != "" ]] || export GOPATH=/go

export PACKAGE_BIN=/usr/src/tools
export PATH=${PACKAGE_BIN}:${GOPATH}/bin:${PATH}
export CC=${CC}
export CGO_ENABLED=${CGO_ENABLED}
export GO111MODULE=${GO111MODULE}

export SNYK_TOKEN=${SNYK_TOKEN}
[[ "${1}" == "" ]] || export SNYK_TOKEN=${1}

gosec -sort ./... 

if [[ "${SNYK_TOKEN}" != "" ]];
then
  snyk -org=nabbar auth ${SNYK_TOKEN}
  snyk -org=nabbar monitor
  snyk test || exit $?
fi

